# Syllabus testing targets

# Default target that runs the test1 target
default: test
test: test1

prep:
    rm -rf lessons
    cp -r lessons-source lessons

test1: prep
    @echo "Running test1 target..."
    syl -v -f syllabus.yaml regroup -l lessons
    syl -v -f syllabus.yaml renumber -l lessons -i 100

test2: prep
    @echo "Running test2"
    syl -e compile -ngm -i100 -l lessons

test3: prep
    @echo "Running test3"
    syl -e compile -ng -i100 -l lessons
    syl -e -vv meta -l lessons
