# Syllabus testing targets

# Default target that runs the test1 target
default: test
test: test1

prep:
    rm -rf lessons
    cp -r lessons-source lessons

test1: prep
    @echo "Running test1 target..."
    syl -v -l lessons regroup
    syl -v -l lessons renumber -i 100

test2: prep
    @echo "Running test2"
    syl -e -l lessons compile -ngm -i100

test3: prep
    @echo "Running test3"
    syl -e -l lessons compile -ng -i100
    syl -e -vv -l lessons meta
